import React from 'react';
import { ArrowLeft, Scale, ShieldAlert, HeartPulse, CreditCard, FileText, UserX, AlertTriangle, Gavel, RefreshCw } from 'lucide-react';

interface TermsOfServiceProps {
  onBack: () => void;
}

const TermsOfService: React.FC<TermsOfServiceProps> = ({ onBack }) => {
  return (
    <div className="flex flex-col h-full bg-white dark:bg-slate-900 transition-colors">
      <header className="px-6 py-6 border-b border-slate-100 dark:border-slate-800 flex items-center gap-4 shrink-0 sticky top-0 bg-white dark:bg-slate-900 z-10">
        <button onClick={onBack} className="p-2 -ml-2 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200">
          <ArrowLeft size={24} />
        </button>
        <h1 className="text-xl font-bold text-slate-900 dark:text-white">Terms of Service</h1>
      </header>

      <div className="flex-1 overflow-y-auto p-6 space-y-8 pb-12">

        {/* Introduction */}
        <section className="bg-primary/5 dark:bg-primary/10 rounded-3xl p-6 border border-primary/10">
          <p className="text-slate-700 dark:text-slate-300 text-sm leading-relaxed">
            Welcome to PulseCoach. By creating an account or using our services, you agree to be bound by these Terms of Service. Please read them carefully before using the application.
          </p>
        </section>

        <section className="space-y-4">
          <div className="flex items-center gap-3 text-primary">
            <div className="p-2 bg-primary/10 rounded-xl">
              <FileText size={20} />
            </div>
            <h2 className="font-black uppercase tracking-wider text-xs">Acceptance of Terms</h2>
          </div>
          <div className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed pl-12">
            <p>By accessing or using PulseCoach, you acknowledge that you have read, understood, and agree to be bound by these Terms. If you do not agree with any part of these terms, you may not use our services.</p>
          </div>
        </section>

        <section className="space-y-4">
          <div className="flex items-center gap-3 text-red-500">
            <div className="p-2 bg-red-100 dark:bg-red-900/30 rounded-xl">
              <ShieldAlert size={20} />
            </div>
            <h2 className="font-black uppercase tracking-wider text-xs">Medical Disclaimer</h2>
          </div>
          <div className="bg-red-50 dark:bg-red-900/20 rounded-2xl p-5 border border-red-100 dark:border-red-900/30 ml-12">
            <p className="text-slate-700 dark:text-slate-300 text-sm leading-relaxed">
              <strong>IMPORTANT:</strong> PulseCoach is an AI-powered fitness tool designed for general wellness purposes. The exercises, routines, and coaching advice provided are generated by artificial intelligence and are <strong>NOT a substitute for professional medical advice, diagnosis, or treatment</strong>.
            </p>
            <p className="text-slate-700 dark:text-slate-300 text-sm leading-relaxed mt-3">
              Always consult with a qualified healthcare provider before starting any new exercise program, especially if you have pre-existing health conditions, injuries, or concerns about your physical ability to exercise safely.
            </p>
          </div>
        </section>

        <section className="space-y-4">
          <div className="flex items-center gap-3 text-primary">
            <div className="p-2 bg-primary/10 rounded-xl">
              <HeartPulse size={20} />
            </div>
            <h2 className="font-black uppercase tracking-wider text-xs">Assumption of Risk</h2>
          </div>
          <div className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed space-y-3 pl-12">
            <p>Physical exercise involves inherent risks of injury, illness, or even death. By using PulseCoach, you acknowledge and accept these risks.</p>
            <p>You agree that:</p>
            <ul className="list-disc list-inside space-y-2 text-slate-500 dark:text-slate-400">
              <li>You are voluntarily participating in physical activities</li>
              <li>You are physically capable of performing the suggested exercises</li>
              <li>You will stop immediately if you experience pain, dizziness, or discomfort</li>
              <li>PulseCoach and its creators are not liable for any injuries sustained while using the app</li>
            </ul>
          </div>
        </section>

        <section className="space-y-4">
          <div className="flex items-center gap-3 text-primary">
            <div className="p-2 bg-primary/10 rounded-xl">
              <CreditCard size={20} />
            </div>
            <h2 className="font-black uppercase tracking-wider text-xs">Subscriptions & Billing</h2>
          </div>
          <div className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed space-y-3 pl-12">
            <p><strong className="text-slate-900 dark:text-white">Free Tier:</strong> Basic access to AI-generated workouts with daily limits.</p>
            <p><strong className="text-slate-900 dark:text-white">Starter Plan:</strong> Enhanced features including calendar integration and extended workout generation.</p>
            <p><strong className="text-slate-900 dark:text-white">Premium Plan:</strong> Full access to all features including AI Voice Coach, Meal Vision scanning, and unlimited workouts.</p>
            <p><strong className="text-slate-900 dark:text-white">Stripe Payments:</strong> Subscriptions billed through Stripe auto-renew monthly unless cancelled at least 24 hours before the renewal date.</p>
            <p><strong className="text-slate-900 dark:text-white">Crypto Payments:</strong> One-time payments via NOWPayments grant access for the specified period. No automatic renewal.</p>
            <p><strong className="text-slate-900 dark:text-white">Refund Policy:</strong> To the extent permitted by applicable law, all payments are non-refundable. Unused subscription time is not eligible for refund upon cancellation.</p>
          </div>
        </section>

        <section className="space-y-4">
          <div className="flex items-center gap-3 text-primary">
            <div className="p-2 bg-primary/10 rounded-xl">
              <Scale size={20} />
            </div>
            <h2 className="font-black uppercase tracking-wider text-xs">User Responsibilities</h2>
          </div>
          <div className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed space-y-3 pl-12">
            <p>You agree to:</p>
            <ul className="list-disc list-inside space-y-2 text-slate-500 dark:text-slate-400">
              <li>Provide accurate information about your fitness level, goals, and equipment</li>
              <li>Use the service only for lawful purposes</li>
              <li>Maintain the security of your account credentials</li>
              <li>Not share your account with others</li>
              <li>Not attempt to reverse-engineer, decompile, or extract our AI algorithms</li>
              <li>Not use automated systems to access the service</li>
            </ul>
          </div>
        </section>

        <section className="space-y-4">
          <div className="flex items-center gap-3 text-primary">
            <div className="p-2 bg-primary/10 rounded-xl">
              <UserX size={20} />
            </div>
            <h2 className="font-black uppercase tracking-wider text-xs">Account Termination</h2>
          </div>
          <div className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed space-y-3 pl-12">
            <p>We reserve the right to suspend or terminate your account if you:</p>
            <ul className="list-disc list-inside space-y-2 text-slate-500 dark:text-slate-400">
              <li>Violate these Terms of Service</li>
              <li>Engage in fraudulent or abusive behavior</li>
              <li>Attempt to bypass payment systems or exploit free trials</li>
              <li>Use the service in ways that could harm other users or our infrastructure</li>
            </ul>
            <p>You may delete your account at any time through the Profile settings.</p>
          </div>
        </section>

        <section className="space-y-4">
          <div className="flex items-center gap-3 text-primary">
            <div className="p-2 bg-primary/10 rounded-xl">
              <AlertTriangle size={20} />
            </div>
            <h2 className="font-black uppercase tracking-wider text-xs">Limitation of Liability</h2>
          </div>
          <div className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed pl-12">
            <p>To the maximum extent permitted by law, PulseCoach and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to personal injury, loss of data, or loss of profits arising from your use of the service.</p>
            <p className="mt-3">Our total liability for any claims arising from your use of PulseCoach shall not exceed the amount you paid us in the twelve months preceding the claim.</p>
          </div>
        </section>

        <section className="space-y-4">
          <div className="flex items-center gap-3 text-primary">
            <div className="p-2 bg-primary/10 rounded-xl">
              <RefreshCw size={20} />
            </div>
            <h2 className="font-black uppercase tracking-wider text-xs">Changes to Terms</h2>
          </div>
          <div className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed pl-12">
            <p>We may update these Terms from time to time. When we make significant changes, we will notify you through the app or via email. Continued use of PulseCoach after changes become effective constitutes acceptance of the revised terms.</p>
          </div>
        </section>

        <section className="space-y-4">
          <div className="flex items-center gap-3 text-primary">
            <div className="p-2 bg-primary/10 rounded-xl">
              <Gavel size={20} />
            </div>
            <h2 className="font-black uppercase tracking-wider text-xs">Governing Law</h2>
          </div>
          <div className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed pl-12">
            <p>These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to its conflict of law provisions. Any disputes arising from these terms shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association.</p>
          </div>
        </section>

        <section className="bg-slate-50 dark:bg-slate-800 rounded-3xl p-6">
          <h3 className="font-black text-xs uppercase tracking-widest text-slate-900 dark:text-white mb-3">Questions?</h3>
          <p className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed">
            If you have any questions about these Terms, contact us at <strong className="text-primary">legal@pulsecoach.app</strong>
          </p>
        </section>

        <div className="pt-8 border-t border-slate-100 dark:border-slate-800 text-center">
          <p className="text-[10px] text-slate-400 uppercase font-bold tracking-widest">
            Last Updated: February 2026
          </p>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
