
import React from 'react';
import { ArrowLeft, Scale, ShieldAlert, HeartPulse, CreditCard } from 'lucide-react';

interface TermsOfServiceProps {
  onBack: () => void;
}

const TermsOfService: React.FC<TermsOfServiceProps> = ({ onBack }) => {
  return (
    <div className="flex flex-col h-full bg-white dark:bg-slate-900 transition-colors">
      <header className="px-6 py-6 border-b border-slate-100 dark:border-slate-800 flex items-center gap-4 shrink-0 sticky top-0 bg-white dark:bg-slate-900 z-10">
        <button onClick={onBack} className="p-2 -ml-2 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200">
          <ArrowLeft size={24} />
        </button>
        <h1 className="text-xl font-bold text-slate-900 dark:text-white">Terms of Service</h1>
      </header>

      <div className="flex-1 overflow-y-auto p-6 space-y-8 pb-12">
        <section className="space-y-4">
          <div className="flex items-center gap-2 text-primary">
            <ShieldAlert size={20} />
            <h2 className="font-bold uppercase tracking-wider text-xs">Medical Disclaimer</h2>
          </div>
          <p className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed">
            PulseCoach is an AI-powered fitness tool. The exercises, routines, and coaching advice provided are generated by artificial intelligence and are <strong>not a substitute for professional medical advice, diagnosis, or treatment</strong>. Always seek the advice of your physician or other qualified health provider before starting any new exercise program.
          </p>
        </section>

        <section className="space-y-4">
          <div className="flex items-center gap-2 text-primary">
            <HeartPulse size={20} />
            <h2 className="font-bold uppercase tracking-wider text-xs">Assumption of Risk</h2>
          </div>
          <p className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed">
            By using PulseCoach, you acknowledge that physical exercise involves inherent risks of injury. You agree that you are voluntarily participating in these activities and assume all risk of injury, illness, or death that might result. PulseCoach and its creators are not liable for any injuries sustained while performing workouts suggested by the app.
          </p>
        </section>

        <section className="space-y-4">
          <div className="flex items-center gap-2 text-primary">
            <CreditCard size={20} />
            <h2 className="font-bold uppercase tracking-wider text-xs">Subscriptions & Billing</h2>
          </div>
          <div className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed space-y-2">
            <p>• <strong>Stripe:</strong> Subscriptions are managed via Stripe and will auto-renew unless cancelled 24 hours before the period ends.</p>
            <p>• <strong>Crypto:</strong> Payments via NOWPayments are one-time transactions. Access is granted for the specific period purchased.</p>
            <p>• <strong>Refunds:</strong> To the extent permitted by law, payments are non-refundable.</p>
          </div>
        </section>

        <section className="space-y-4">
          <div className="flex items-center gap-2 text-primary">
            <Scale size={20} />
            <h2 className="font-bold uppercase tracking-wider text-xs">User Conduct</h2>
          </div>
          <p className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed">
            Users must provide accurate information regarding their fitness level and equipment. Misuse of the platform, including attempting to reverse-engineer the AI coaching logic or bypass payment gateways, will result in immediate account termination.
          </p>
        </section>

        <div className="pt-8 border-t border-slate-100 dark:border-slate-800 text-center">
          <p className="text-[10px] text-slate-400 uppercase font-medium tracking-widest">
            Last Updated: May 2024
          </p>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
